#!/usr/bin/env python3
"""Reconcile Claude Code configuration into Codex without touching Codex-only entries."""
from __future__ import annotations

import argparse
import fcntl
import hashlib
import json
import os
import pathlib
import shutil
import subprocess
import sys
import time
from typing import Any

import tomlkit

HOME = pathlib.Path.home()
STATE_DIR = HOME / ".cache/codex-config-sync"
GENERATED_MARKER = "<!-- GENERATED BY codex-config-sync; edit CLAUDE.md and .ai-config/AGENTS.codex.md -->"


def git_root(path: pathlib.Path) -> pathlib.Path:
    return pathlib.Path(subprocess.check_output(["git", "rev-parse", "--show-toplevel"], cwd=path, text=True).strip()).resolve()


def load_json(path: pathlib.Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    value = json.loads(path.read_text())
    if not isinstance(value, dict):
        raise RuntimeError(f"expected object in {path}")
    return value


def source_fingerprint(root: pathlib.Path) -> str:
    digest = hashlib.sha256()
    files = [HOME / ".claude/settings.json", HOME / ".claude/CLAUDE.md", root / "CLAUDE.md", root / ".mcp.json", root / ".ai-config/AGENTS.codex.md"]
    for directory in (HOME / ".claude/agents", HOME / ".claude/commands", HOME / ".claude/hooks", HOME / ".claude/rules", HOME / ".claude/skills", root / ".claude"):
        if directory.is_dir():
            files.extend(p for p in directory.rglob("*") if p.is_file() and p.name != ".mcp.local.env")
    for path in sorted(set(files), key=str):
        if path.is_file():
            digest.update(str(path).encode())
            digest.update(path.read_bytes())
    claude = load_json(HOME / ".claude.json")
    selected = {"global": claude.get("mcpServers", {}), "project": (claude.get("projects", {}).get(str(root), {}) or {}).get("mcpServers", {})}
    digest.update(json.dumps(selected, sort_keys=True, separators=(",", ":")).encode())
    return digest.hexdigest()


def sync_instructions(root: pathlib.Path) -> list[str]:
    claude = root / "CLAUDE.md"
    agents = root / "AGENTS.md"
    overlay = root / ".ai-config/AGENTS.codex.md"
    if not claude.is_file():
        return []
    changed: list[str] = []
    if not overlay.exists():
        overlay.parent.mkdir(parents=True, exist_ok=True)
        original = agents.read_text() if agents.is_file() and not agents.read_text().startswith(GENERATED_MARKER) else "# Codex-specific project instructions\n"
        overlay.write_text(original.rstrip() + "\n")
        changed.append(str(overlay))
    generated = GENERATED_MARKER + "\n\n" + claude.read_text().rstrip() + "\n\n---\n\n# Codex-specific overlay\n\n" + overlay.read_text().rstrip() + "\n"
    if not agents.is_file() or agents.read_text() != generated:
        agents.write_text(generated)
        changed.append(str(agents))
    return changed


def claude_mcp_maps(root: pathlib.Path) -> tuple[dict[str, Any], dict[str, Any]]:
    claude = load_json(HOME / ".claude.json")
    global_servers = dict(claude.get("mcpServers", {}) or {})
    project_servers = dict((claude.get("projects", {}).get(str(root), {}) or {}).get("mcpServers", {}) or {})
    shared = load_json(root / ".mcp.json").get("mcpServers", {}) or {}
    project_servers.update(shared)
    return global_servers, project_servers


def sync_toml_mcp(path: pathlib.Path, servers: dict[str, Any], previous_managed: set[str]) -> list[str]:
    path.parent.mkdir(parents=True, exist_ok=True)
    doc = tomlkit.parse(path.read_text()) if path.is_file() else tomlkit.document()
    existing = doc.get("mcp_servers")
    if existing is None:
        existing = tomlkit.table()
        doc["mcp_servers"] = existing
    changed: list[str] = []
    for name in sorted(previous_managed - set(servers)):
        if name in existing:
            del existing[name]
            changed.append(f"removed:{name}")
    for name, source in sorted(servers.items()):
        if not isinstance(source, dict):
            raise RuntimeError(f"invalid MCP definition: {name}")
        old = existing.get(name)
        table = tomlkit.table()
        if old is not None:
            for key, value in old.items():
                if key not in {"command", "args", "url", "env", "cwd"}:
                    table[key] = value
        if source.get("url"):
            table["url"] = str(source["url"])
        else:
            if not source.get("command"):
                raise RuntimeError(f"stdio MCP server {name} lacks command")
            table["command"] = str(source["command"])
            table["args"] = [str(x) for x in source.get("args", [])]
            if source.get("env"):
                table["env"] = {str(k): str(v) for k, v in source["env"].items()}
        existing[name] = table
        changed.append(f"updated:{name}")
    rendered = tomlkit.dumps(doc)
    if not path.is_file() or path.read_text() != rendered:
        path.write_text(rendered)
    else:
        changed = []
    return changed


def sync_skills(previous_managed: set[str]) -> tuple[list[str], list[str]]:
    source_root = HOME / ".claude/skills"
    target_root = HOME / ".agents/skills"
    target_root.mkdir(parents=True, exist_ok=True)
    current = {p.name for p in source_root.iterdir() if p.is_dir()} if source_root.is_dir() else set()
    changed: list[str] = []
    for name in sorted(previous_managed - current):
        target = target_root / name
        if target.is_symlink() or target.exists():
            if target.is_dir() and not target.is_symlink():
                shutil.rmtree(target)
            else:
                target.unlink()
            changed.append(f"removed:{name}")
    for name in sorted(current):
        source = source_root / name
        target = target_root / name
        if target.is_symlink() and target.resolve() == source.resolve():
            continue
        if target.is_dir() and not target.is_symlink():
            shutil.rmtree(target)
        elif target.exists() or target.is_symlink():
            target.unlink()
        target.symlink_to(source, target_is_directory=True)
        changed.append(f"linked:{name}")
    return sorted(current), changed


def sync_plugins() -> list[str]:
    settings = load_json(HOME / ".claude/settings.json").get("enabledPlugins", {}) or {}
    path = HOME / ".codex/config.toml"
    doc = tomlkit.parse(path.read_text())
    plugins = doc.get("plugins")
    if plugins is None:
        return []
    # These Claude hook plugins are either incompatible with Codex or stale
    # output styles that must not survive after Claude stops enabling them.
    compatibility_disabled = {
        "security-guidance@claude-plugins-official",
        "explanatory-output-style@claude-plugins-official",
        "learning-output-style@claude-plugins-official",
    }
    changed = []
    managed_names = set(settings) | compatibility_disabled
    for name in sorted(managed_names):
        if name not in plugins:
            continue
        desired = bool(settings.get(name, False)) and name not in compatibility_disabled
        if bool(plugins[name].get("enabled", True)) != desired:
            plugins[name]["enabled"] = desired
            changed.append(f"{name}:{str(desired).lower()}")
    rendered = tomlkit.dumps(doc)
    if path.read_text() != rendered:
        path.write_text(rendered)
    return changed


def sync_global_features(path: pathlib.Path) -> list[str]:
    """Apply global Codex feature settings managed by this dotfiles repository."""
    path.parent.mkdir(parents=True, exist_ok=True)
    doc = tomlkit.parse(path.read_text()) if path.is_file() else tomlkit.document()
    features = doc.get("features")
    if features is None:
        features = tomlkit.table()
        doc["features"] = features
    if features.get("default_mode_request_user_input") is True:
        return []
    features["default_mode_request_user_input"] = True
    path.write_text(tomlkit.dumps(doc))
    return ["default_mode_request_user_input:true"]


def sync_hook_scripts() -> list[str]:
    target_root = HOME / ".codex/hooks"
    target_root.mkdir(parents=True, exist_ok=True)
    changed: list[str] = []
    for name in ("reinject-on-compact.sh", "save-insights-reminder.sh"):
        source = HOME / ".claude/hooks" / name
        target = target_root / name
        if not source.is_file():
            raise RuntimeError(f"missing Claude hook source: {source}")
        if target.is_symlink() and target.resolve() == source.resolve():
            continue
        if target.exists() or target.is_symlink():
            target.unlink()
        target.symlink_to(source)
        changed.append(f"linked:{name}")
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cwd", default=os.getcwd())
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--quiet", action="store_true")
    parser.add_argument("--compat-only", action="store_true")
    parser.add_argument("--restart-daemon-on-change", action="store_true")
    args = parser.parse_args()
    STATE_DIR.mkdir(parents=True, exist_ok=True)

    if args.compat_only:
        state_file = STATE_DIR / "compat.json"
        with (STATE_DIR / "compat.lock").open("w") as lock:
            fcntl.flock(lock, fcntl.LOCK_EX)
            state = load_json(state_file)
            hook_changes = sync_hook_scripts()
            skills, skill_changes = sync_skills(set(state.get("skillNames", [])))
            feature_changes = sync_global_features(HOME / ".codex/config.toml")
            plugin_changes = sync_plugins()
            result = {
                "status": "ok",
                "skills": skill_changes,
                "features": feature_changes,
                "plugins": plugin_changes,
                "hooks": hook_changes,
            }
            state.update({
                "skillNames": skills,
                "updatedAt": int(time.time()),
                "lastCompatResult": result,
            })
            state_file.write_text(json.dumps(state, indent=2) + "\n")
            if not args.quiet:
                print(json.dumps(result, indent=2))
        return 0

    root = git_root(pathlib.Path(args.cwd).expanduser().resolve())
    key = hashlib.sha256(str(root).encode()).hexdigest()
    state_file = STATE_DIR / f"{key}.json"
    with (STATE_DIR / f"{key}.lock").open("w") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        state = load_json(state_file)
        fingerprint = source_fingerprint(root)
        hook_changes = sync_hook_scripts()
        feature_changes = sync_global_features(HOME / ".codex/config.toml")
        if not args.force and state.get("fingerprint") == fingerprint and not hook_changes and not feature_changes:
            if not args.quiet:
                print(json.dumps({"status": "unchanged", "root": str(root)}))
            return 0
        instructions = sync_instructions(root)
        global_mcp, project_mcp = claude_mcp_maps(root)
        global_changes = sync_toml_mcp(HOME / ".codex/config.toml", global_mcp, set(state.get("globalMcpNames", [])))
        project_changes = sync_toml_mcp(root / ".codex/config.toml", project_mcp, set(state.get("projectMcpNames", [])))
        skills, skill_changes = sync_skills(set(state.get("skillNames", [])))
        plugin_changes = sync_plugins()
        result = {"status": "ok", "root": str(root), "instructions": instructions, "globalMcp": global_changes, "projectMcp": project_changes, "skills": skill_changes, "features": feature_changes, "plugins": plugin_changes, "hooks": hook_changes}
        state_file.write_text(json.dumps({"fingerprint": source_fingerprint(root), "globalMcpNames": sorted(global_mcp), "projectMcpNames": sorted(project_mcp), "skillNames": skills, "updatedAt": int(time.time()), "lastResult": result}, indent=2) + "\n")
        if not args.quiet:
            print(json.dumps(result, indent=2))
    # Never restart while holding the project lock: ExecStartPre runs this
    # synchronizer and would otherwise wait on the lock held by this process.
    if args.restart_daemon_on_change:
        active = subprocess.run(["systemctl", "--user", "is-active", "--quiet", "codex-app-server.service"]).returncode == 0
        if active:
            if not args.quiet:
                print("Configuration changed; restarting Codex App Server (graceful MCP shutdown can take about 30 seconds)...", file=sys.stderr, flush=True)
            subprocess.run(["systemctl", "--user", "restart", "codex-app-server.service"], check=True)
            socket = HOME / ".codex/app-server-control/app-server-control.sock"
            deadline = time.monotonic() + 90
            while time.monotonic() < deadline and not socket.is_socket():
                time.sleep(1)
            if not socket.is_socket():
                raise RuntimeError(f"Codex App Server restarted but socket was not ready after 90s: {socket}")
            if not args.quiet:
                print("Codex App Server is ready.", file=sys.stderr, flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
